apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapp
        env: development
    spec:
      containers:
      - name: nodeapp
        image: gcr.io/candidate-6/nodeapp:v1
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: candidate-6-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
<<<<<<< HEAD
    app: nodeapp
    
=======
    app: candidate-6
>>>>>>> 74378935973a276153ff22f0fab7b17806114d6d
