apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  labels:
    app: nodeapp
spec:
#  type: LoadBalancer
  type: NodePort # NodePort + LoadBalancer enable external access (from internet) to this Service. NodePort is usually for testing. LoadBalancer Service is cloud specific (and can become expensive). Ingress Load Balancer could be the better choice.
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30001 # <-- Port 30000 is taken for minikube's dashboard
  selector:
      app: nodeapp
---
apiVersion: apps/v1 #extensions/v1beta1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  replicas: 1
  selector: # Needed for new apiVersion: apps/v1, NOT for extensions/v1beta1
      matchLabels:
        app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: k8s-node-api
        imagePullPolicy: Never
        ports:
        - containerPort: 3000